### ISSUE TITLE
Cannot create new project on Manjaro KDE with AppImage distribution

### ISSUE THREAD

**Issue by TapGhoul** [shishome/fractal#10]
Current Version: 0.0.0  (Can be retrieved from Fractal Credits)

Issue Type: bug 

**Version**
0.1.0 release, from GitHub releases

**Environment:**
**OS**
[ ] Windows (Specify Version)
[ ] MacOS (Specify Version)
[x] Linux - Manjaro KDE

**Arch**
[x] x86_64 (Generally the correct option)
[ ] i386
[ ] ARM64

**Issue Description:**
Provide a detailed description here
Trying to open a project fails with "cannot read properties of undefined"

**Steps to reproduce:**
Provide a detailed instruction set to reproduce the issue
- Open the program
- Hit new project
- Notice issue in the console

Attachments: Yes
Place any attachements in the issue that can help us reproduce. Screenshots or Screen Recordings. 
![image](https://user-images.githubusercontent.com/3120639/143381880-612a7b9d-1591-47b6-8183-9abf59955339.png)
![image](https://user-images.githubusercontent.com/3120639/143382100-e808c91f-5ddb-4980-acff-988075e7257e.png)
```
System:    Host: Taps-Nuc Kernel: 5.10.79-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.23.3 Distro: Manjaro Linux
Machine:   Type: Desktop System: Intel product: NUC8i7HVK v: J71485-502 serial: <superuser required>
           Mobo: Intel model: NUC8i7HVB v: J68196-502 serial: <superuser required> UEFI: Intel
           v: HNKBLi70.86A.0029.2018.0222.1606 date: 02/22/2018
CPU:       Info: Quad Core model: Intel Core i7-8809G bits: 64 type: MT MCP cache: L2: 1024 KiB
           Speed: 1706 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 2171 2: 2159 3: 2183 4: 2169 5: 2261 6: 2293 7: 2100
           8: 2109
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 XT [Radeon RX Vega M GH] driver: amdgpu v: kernel
           Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo
           Display: x11 server: X.Org 1.21.1.1 driver: loaded: amdgpu,ati,modesetting resolution: 1: 1920x1080 2: 1920x1080
           OpenGL: renderer: AMD VEGAM (DRM 3.40.0 5.10.79-1-MANJARO LLVM 13.0.0) v: 4.6 Mesa 21.2.5
Audio:     Device-1: Intel CM238 HD Audio driver: snd_hda_intel
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 HDMI Audio driver: snd_hda_intel
           Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo
           Device-4: C-Media Blue Snowball type: USB driver: hid-generic,snd-usb-audio,usbhid
           Sound Server-1: ALSA v: k5.10.79-1-MANJARO running: yes
           Sound Server-2: PipeWire v: 0.3.40 running: yes
Network:   Device-1: Intel Ethernet I219-LM driver: e1000e
           IF: enp0s31f6 state: down mac: 54:b2:03:04:70:3f
           Device-2: Intel I210 Gigabit Network driver: igb
           IF: enp5s0 state: down mac: 54:b2:03:04:70:40
           Device-3: Intel Wireless 8265 / 8275 driver: iwlwifi
           IF: wlp6s0 state: up mac: 0c:54:15:6e:b4:28
           IF-ID-1: virbr0 state: down mac: 52:54:00:22:c5:8a
Bluetooth: Device-1: Intel Bluetooth wireless interface type: USB driver: btusb
           Report: rfkill ID: hci0 state: up address: see --recommends
Drives:    Local Storage: total: 931.51 GiB used: 713.04 GiB (76.5%)
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 1TB size: 931.51 GiB
Partition: ID-1: / size: 906.94 GiB used: 713 GiB (78.6%) fs: ext4 dev: /dev/dm-0
           ID-2: /boot/efi size: 299.4 MiB used: 428 KiB (0.1%) fs: vfat dev: /dev/nvme0n1p1
Swap:      ID-1: swap-1 type: partition size: 8.8 GiB used: 36 MiB (0.4%) dev: /dev/dm-1
Sensors:   System Temperatures: cpu: 65.0 C pch: 47.0 C mobo: 27.8 C gpu: amdgpu temp: 52.0 C
           Fan Speeds (RPM): N/A
Info:      Processes: 295 Uptime: 8h 32m Memory: 15.55 GiB used: 7.37 GiB (47.4%) Shell: Bash inxi: 3.3.09
```

**Comment by shishome** [comment]
https://github.com/electron/electron/issues/2911#issuecomment-461932357

this seems related. Seems to be an issue with GtkFileChooser? Will try in the morning.

**Comment by shishome** [comment]
![Screenshot from 2021-11-25 00-25-08](https://user-images.githubusercontent.com/77416508/143384586-c8ba17ca-9bec-40c8-8dd9-099e36da57d4.png)

Reproduced v0.1.0 in Manjaro KDE 21.1.6, Fresh Install, live-cd environment

**Comment by shishome** [comment]
https://github.com/electron/electron/issues/31152

This is a known issue with Electron and is being worked on. When upstream fixes, I will merge in the changes by bumping the electron version.

**Comment by shishome** [comment]
Workaround as mentioned in a comment on the root issue https://github.com/ArchipelagoMW/SuperMetroidClient/commit/e00d60680ae48e743ac5f0177892e475c21df5ea

I don't think I'm going to implement this though, because it only affects a small subset and using async is a bit of a pain. Better to wait for the fix imo.
